// Generated by CoffeeScript 1.8.0
(function() {
  var BOARD_HEIGHT, BOARD_WIDTH, CALC_BUFFER, SQUARE_SIZE, board, canvas, clearCell, ctx, drawGrid, drawLine, fillCell, getLiveNeighbors, getMousePos, i, toggleCell, update, _i, _ref;

  SQUARE_SIZE = 30;

  BOARD_WIDTH = 40;

  BOARD_HEIGHT = 30;

  CALC_BUFFER = 2;

  drawGrid = function() {
    var i, _i, _j, _ref, _ref1, _results;
    for (i = _i = 0.5, _ref = canvas.width + 0.5; SQUARE_SIZE > 0 ? _i <= _ref : _i >= _ref; i = _i += SQUARE_SIZE) {
      drawLine(ctx, i, 0, i, canvas.height);
    }
    _results = [];
    for (i = _j = 0.5, _ref1 = canvas.height + 0.5; SQUARE_SIZE > 0 ? _j <= _ref1 : _j >= _ref1; i = _j += SQUARE_SIZE) {
      _results.push(drawLine(ctx, 0, i, canvas.width, i));
    }
    return _results;
  };

  drawLine = function(ctx, sx, sy, fx, fy) {
    ctx.moveTo(sx, sy);
    ctx.lineTo(fx, fy);
    return ctx.stroke();
  };

  getMousePos = function(canvas, evt) {
    var rect;
    rect = canvas.getBoundingClientRect();
    return {
      x: evt.clientX - rect.left,
      y: evt.clientY - rect.top
    };
  };

  toggleCell = function(rawX, rawY) {
    var cellX, cellY;
    cellX = Math.floor(rawX / SQUARE_SIZE) + CALC_BUFFER;
    cellY = Math.floor(rawY / SQUARE_SIZE) + CALC_BUFFER;
    board[cellX][cellY] = !board[cellX][cellY];
    if (board[cellX][cellY]) {
      return fillCell(rawX, rawY);
    } else {
      return clearCell(rawX, rawY);
    }
  };

  fillCell = function(rawX, rawY) {
    var x, y;
    x = Math.floor(rawX / SQUARE_SIZE) * SQUARE_SIZE + 1;
    y = Math.floor(rawY / SQUARE_SIZE) * SQUARE_SIZE + 1;
    return ctx.fillRect(x, y, SQUARE_SIZE - 1, SQUARE_SIZE - 1);
  };

  clearCell = function(rawX, rawY) {
    var x, y;
    x = Math.floor(rawX / SQUARE_SIZE) * SQUARE_SIZE + 1;
    y = Math.floor(rawY / SQUARE_SIZE) * SQUARE_SIZE + 1;
    return ctx.clearRect(x, y, SQUARE_SIZE - 1, SQUARE_SIZE - 1);
  };

  update = function() {};

  getLiveNeighbors = function(row, col) {};

  canvas = document.getElementById('board');

  canvas.width = SQUARE_SIZE * BOARD_WIDTH + 1;

  canvas.height = SQUARE_SIZE * BOARD_HEIGHT + 1;

  ctx = canvas.getContext('2d');

  ctx.strokeStyle = '#ccc';

  ctx.fillStyle = 'red';

  drawGrid();

  board = new Array(BOARD_HEIGHT + 2 * CALC_BUFFER);

  for (i = _i = 0, _ref = board.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
    board[i] = new Array(BOARD_WIDTH + 2 * CALC_BUFFER);
  }

  console.log(board);

  canvas.addEventListener('click', function(evt) {
    var mousePos;
    mousePos = getMousePos(canvas, evt);
    return toggleCell(mousePos.x, mousePos.y);
  }, false);

  document.getElementById('step').addEventListener('click', update, false);

  document.getElementById('reset').addEventListener('click', function() {
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    return drawGrid();
  }, false);

}).call(this);
