// Generated by CoffeeScript 1.8.0
(function() {
  var BOARD_HEIGHT, BOARD_WIDTH, CALC_BUFFER, SQUARE_SIZE, active, canvas, clearCell, ctx, drawGrid, drawLine, fillCell, getLiveNeighbors, getMousePos, toggleCell, update;

  SQUARE_SIZE = 30;

  BOARD_WIDTH = 40;

  BOARD_HEIGHT = 30;

  CALC_BUFFER = 2;

  drawGrid = function() {
    var i, _i, _j, _ref, _ref1, _results;
    for (i = _i = 0.5, _ref = canvas.width + 0.5; SQUARE_SIZE > 0 ? _i <= _ref : _i >= _ref; i = _i += SQUARE_SIZE) {
      drawLine(ctx, i, 0, i, canvas.height);
    }
    _results = [];
    for (i = _j = 0.5, _ref1 = canvas.height + 0.5; SQUARE_SIZE > 0 ? _j <= _ref1 : _j >= _ref1; i = _j += SQUARE_SIZE) {
      _results.push(drawLine(ctx, 0, i, canvas.width, i));
    }
    return _results;
  };

  drawLine = function(ctx, sx, sy, fx, fy) {
    ctx.moveTo(sx, sy);
    ctx.lineTo(fx, fy);
    return ctx.stroke();
  };

  getMousePos = function(canvas, evt) {
    var rect;
    rect = canvas.getBoundingClientRect();
    return {
      x: evt.clientX - rect.left,
      y: evt.clientY - rect.top
    };
  };

  toggleCell = function(rawX, rawY) {
    var cellX, cellY, idx;
    cellX = Math.floor(rawX / SQUARE_SIZE) + CALC_BUFFER;
    cellY = Math.floor(rawY / SQUARE_SIZE) + CALC_BUFFER;
    idx = -1;
    if (typeof active[cellY] === 'undefined') {
      active[cellY] = [];
    } else {
      idx = active[cellY].indexOf(cellX);
    }
    if (idx === -1) {
      fillCell(rawX, rawY);
      return active[cellY].unshift(cellX);
    } else {
      clearCell(rawX, rawY);
      if (active[cellY].length === 1) {
        return active.splice(cellY, cellY + 1);
      } else {
        return active[cellY].splice(idx, idx + 1);
      }
    }
  };

  fillCell = function(rawX, rawY) {
    var x, y;
    x = Math.floor(rawX / SQUARE_SIZE) * SQUARE_SIZE + 1;
    y = Math.floor(rawY / SQUARE_SIZE) * SQUARE_SIZE + 1;
    return ctx.fillRect(x, y, SQUARE_SIZE - 1, SQUARE_SIZE - 1);
  };

  clearCell = function(rawX, rawY) {
    var x, y;
    x = Math.floor(rawX / SQUARE_SIZE) * SQUARE_SIZE + 1;
    y = Math.floor(rawY / SQUARE_SIZE) * SQUARE_SIZE + 1;
    return ctx.clearRect(x, y, SQUARE_SIZE - 1, SQUARE_SIZE - 1);
  };

  update = function() {};

  getLiveNeighbors = function(row, col) {
    var i, neighborList, r, _i, _j, _ref, _ref1, _ref2, _ref3;
    neighborList = [];
    for (r = _i = _ref = row - 1, _ref1 = row + 1; _i <= _ref1; r = _i += 2) {
      if (typeof active[r] !== 'undefined') {
        for (i = _j = _ref2 = col - 1, _ref3 = col + 1; _ref2 <= _ref3 ? _j <= _ref3 : _j >= _ref3; i = _ref2 <= _ref3 ? ++_j : --_j) {
          if (typeof active[r][i] !== 'undefined') {
            neighborList.add(active[r][i]);
          }
        }
      }
    }
    if (typeof active[row][col - 1] !== void 0) {
      neighborList.add(active[row][col - 1]);
    }
    if (typeof active[row][col + 1] !== void 0) {
      neighborList.add(active[row][col + 1]);
    }
    return neighborList;
  };

  canvas = document.getElementById('board');

  canvas.width = SQUARE_SIZE * BOARD_WIDTH + 1;

  canvas.height = SQUARE_SIZE * BOARD_HEIGHT + 1;

  active = [];

  ctx = canvas.getContext('2d');

  ctx.strokeStyle = '#ccc';

  ctx.fillStyle = 'red';

  drawGrid();

  canvas.addEventListener('click', function(evt) {
    var mousePos;
    mousePos = getMousePos(canvas, evt);
    return toggleCell(mousePos.x, mousePos.y);
  }, false);

  document.getElementById('step').addEventListener('click', update, false);

  document.getElementById('reset').addEventListener('click', function() {
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    return drawGrid();
  }, false);

}).call(this);
